name: CI

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - uses: pnpm/action-setup@v2.0.1
      with:
        version: 6.7.4

    - run: pnpm install
    - run: npm run lint:git
    - run: npm run lint:js

  test:
    needs: lint

    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        node:
        - 12
        - '*'
        exclude:
        - os: macos-latest
          node: '*'

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}
    - uses: pnpm/action-setup@v2.0.1
      with:
        version: 6.7.4

    - run: pnpm install
    - run: npm test
      continue-on-error: ${{ matrix.os == 'macos-latest' }}
      env:
        TEST_TYPE: addon
        DEBUG: ember-cli-update,boilerplate-update,git-diff-apply

  ember-cli-update:
    needs: test
    if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        token: ${{ secrets.GitHubToken }}
    - uses: actions/setup-node@v2
    - uses: pnpm/action-setup@v2.0.1
      with:
        version: 6.7.4
    - uses: kellyselden/ember-cli-update-action@v3
      with:
        autofix_command: npm run lint:js -- --fix
        ignore_to: true
        commit_prefix: "chore: "
