name: Publish

on:
  push:
    branches:
    - main
    tags: '*@[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version: 18

        registry-url: 'https://registry.npmjs.org'

    - run: npm run release
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
