name: Publish

on:
  push:
    branches:
    - main
    tags: '*@[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

      with:
        fetch-depth: 0

    - run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

    - uses: actions/setup-node@v4
      with:
        node-version: 20

        registry-url: 'https://registry.npmjs.org'

    - uses: pnpm/action-setup@v4.1.0
      with:
        version: 8.15.9

    - run: pnpm install

    - run: npm run release
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
